# Generated by Django 5.1.6 on 2025-02-11 12:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_colorvarient_sizevarient_product_color_varients_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='color_varients',
            field=models.ManyToManyField(blank=True, to='products.colorvarient'),
        ),
        migrations.AlterField(
            model_name='product',
            name='size_varients',
            field=models.ManyToManyField(blank=True, to='products.sizevarient'),
        ),
    ]
